kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: crypto-monitor-api-hostpath
provisioner: microk8s.io/hostpath
reclaimPolicy: Delete
parameters:
  pvDir: /root/cluster-data/crypto-monitor-api
volumeBindingMode: WaitForFirstConsumer
