name: Deploy to Firebase
on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Firebase
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v3
        with:
          version: '8'
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'pnpm'
      - uses: nrwl/nx-set-shas@v3
        with:
          error-on-no-successful-workflow: false
      - run: pnpm i --frozen-lockfile
      - run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GUND_CRYPTO_MONITOR }}' > firebase-service-account.json
        name: Authorize Firebase
      - run: npx nx affected --target=deploy-firebase
        name: Deploying to Firebase
        env:
          GOOGLE_APPLICATION_CREDENTIALS: firebase-service-account.json
          SSM_API_URL: ${{ secrets.SSM_API_URL }}
      - run: rm firebase-service-account.json
        name: Post Authorize Firebase
        if: always()
