name: Deploy to Firebase

on:
  workflow_run:
    workflows: [Test]
    types: [completed]
    branches: [main]

permissions:
  actions: read
  contents: read

env:
  NX_CLOUD_AUTH_TOKEN: ${{ secrets.NX_CLOUD_AUTH_TOKEN }}

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment: Firebase
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v3
        with:
          version: '8'
      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'pnpm'
      - run: pnpm i --frozen-lockfile
      - uses: nrwl/nx-set-shas@v3
      - name: Firebase - Authorize
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GUND_CRYPTO_MONITOR }}' > firebase-service-account.json
      - name: Firebase - Deploy
        run: npx nx affected -t firebase-deploy --skip-nx-cache
        env:
          GOOGLE_APPLICATION_CREDENTIALS: firebase-service-account.json
          SSM_API_URL: ${{ secrets.SSM_API_URL }}
      - name: Post Firebase - Authorize
        run: rm firebase-service-account.json
        if: always()
